---
- name: Generate SSH key pair
  hosts: localhost
  gather_facts: false

  vars:
    key_name: "aap-demo-{{ lookup('pipe','date +%s') }}"

  tasks:

    - name: Generate private key (native)
      ansible.builtin.command:
        cmd: ssh-keygen -t rsa -b 2048 -f /tmp/{{ key_name }} -N ""
      args:
        creates: "/tmp/{{ key_name }}"

    - name: Read private key
      ansible.builtin.slurp:
        src: "/tmp/{{ key_name }}"
      register: private_key

    - name: Read public key
      ansible.builtin.slurp:
        src: "/tmp/{{ key_name }}.pub"
      register: public_key

    - name: Save artifacts
      ansible.builtin.set_stats:
        data:
          ssh_private_key: "{{ private_key.content | b64decode }}"
          ssh_public_key: "{{ public_key.content | b64decode }}"
          key_name: "{{ key_name }}"
        per_host: false