- hosts: localhost
  gather_facts: false
  tasks:
    - command: curl -I https://www.google.com
      register: curl_google
      ignore_errors: true

    - debug:
        var: curl_google

    - command: curl -k -v --connect-timeout 10 https://api.cluster-v8jc8.dynamic.redhatworkshops.io:6443/version
      register: curl_ocp
      ignore_errors: true

    - debug:
        var: curl_ocp